version: '3.8'

services:
  fastmcp-docs-server:
    build: .
    ports:
      - "8001:8001"
    environment:
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8001
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s